# Database vars
pg_db_name: nautobot
pg_user: nautobot
pg_password: nautobot
# Nautobot web vars
cert_path: "/etc/ssl"
cert_country: US
cert_state: CO
cert_city: Denver
cert_domain: "nautobot-demo.byrnbaker.local"
nautobot_http_port: 80
nautobot_https_port: 443
venv_dir: /opt/nautobot
requirements:
    - name: napalm
    - name: nornir-nautobot
    - name: nautobot-golden-config
    - name: nautobot-device-onboarding
nautobot_config:
  allowed_hosts: 
    - prfx: '*'
  napalm_user: nautobot
  napalm_passwd: N@utobot123
  nautobot_plugins:
    - name: nautobot_plugin_nornir
    - name: nautobot_golden_config
    - name: nautobot_device_onboarding
  nautobot_plugin_config:
    nautobot_plugin_nornir:
      nornir_settings:
        credentials: "nautobot_plugin_nornir.plugins.credentials.env_vars.CredentialsEnvVars"
        runner:
          plugin: "threaded"
          options:
            num_workers: 20
    nautobot_golden_config:
      per_feature_bar_width: 0.15
      per_feature_width: 13
      per_feature_height: 4
      enable_backup: True
      enable_compliance: True
      enable_intended: True
      enable_sotagg: True
      sot_agg_transposer: None
      default_drivers_mapping: None